name: Metrics Collector

on:
  push:
  pull_request:

jobs:
  collect-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: collect-metrics
        uses: ./.github/actions/metrics
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          mongo-password: ${{secrets.MONGO_PWD}}
